config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  devise_for :models
  resources :users
  resources :outfits
  resources :items
  get 'outfits/new', to:'outfits#new', as: 'new'
  post '/rate' => 'rater#create', :as => 'rate'

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :outfit
  mount_uploader :image, ImageUploader
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/outfit.rb
class Outfit < ActiveRecord::Base
	  # ratyrate_rateable "Hype level"
		has_many :items
		ratyrate_rateable 'Appeal'
		ratyrate_rater

		belongs_to :user
		validates :name, presence: true, uniqueness: true
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ratyrate_rater
  has_many :outfits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    current_user = current_user
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    @item = Item.new(:outfit_id => params[:outfit_id])
  end

  def create
    @item = Item.new(outfit_id:params[:item][:outfit_id], name:params[:item][:name], image:params[:item][:image])
    if @item.save
      flash[:notice] = "Successfully created item."
      redirect_to outfit_path(params[:item][:outfit_id])
    else
      render :action => 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(params[:item])
      flash[:notice] = "Successfully updated item."
      redirect_to @item.outfit
    else
      render :action => 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    flash[:notice] = "Successfully destroyed item."
    redirect_to @item.outfit
  end

end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  def index
    @outfits = Outfit.all
  end

  def show
    @outfit = Outfit.find(params[:id])
  end

  def new
    @outfit = Outfit.new()
  end

  def create
     puts current_user
     @outfit = Outfit.new(name:params[:outfit][:name], user_id:current_user)
     if @outfit.save
       flash[:notice] = "Successfully created outfit."
       redirect_to @outfit
     else
       render :action => 'new'
     end
   end

   def edit
     @outfit = Outfit.find(params[:id])
   end

   def update
     @outfit = Outfit.find(params[:id])
     if @outfit.update_attributes(params[:outfit])
       flash[:notice] = "Successfully updated outfit."
       redirect_to outfit_url
     else
       render :action => 'edit'
     end
   end

   def destroy
     @outfit = Outfit.find(params[:id])
     @outfit.destroy
     flash[:notice] = "Successfully destroyed outfit."
     redirect_to outfits_url
   end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @outfits = Outfit.where(user_id:@user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
    @outfits = Outfit.all
  end

  def show
    @user = current_user
    @outfits = Outfit.where(user_id:current_user)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/grayscale.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading" style="color:#33cccc">#OOTD</h1>
                        <p class="intro-text">Forgot that awesome outfit?<br>Never again.</p>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/grayscale.js"></script>

</body>

</html>

app/views/items/_form.html.erb
<%= form_for @item, :html => {:multipart => true} do |f| %>
  <%= f.hidden_field :outfit_id %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/items/edit.html.erb
 <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
<h1>Edit Item</h1>

<%= render 'form' %>

<p><%= link_to "Back to Outfit", @item.outfit %></p>

app/views/items/new.html.erb
 <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
<h1>New Item</h1>

<%= render 'form' %>

<p><%= link_to "Back to Outfit", @item.outfit %></p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit Your Profile', edit_user_registration_path %></li>
    <li>  <%=link_to 'View your outfits'
  %></li>
  <li><%= link_to 'Log Out', destroy_user_session_path, :method=>'delete' %></li>

<% else %>
  <li><%= link_to 'Log In', new_user_session_path %></li>
  <li><%= link_to 'Sign Up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "OOTD" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blog" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/outfits/_form.html.erb
<%= form_for @outfit do |f| %>
  <%= f.hidden_field :user_id %>
  <p>
    <%= f.label :name %><br /></div>
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/outfits/edit.html.erb
<h1> Edit Outfits </h1>

<%= render 'form' %>

<p>
  <%= link_to "Show", @outfit %> |
  <%= link_to "View All", outfits_path %>
</p>

app/views/outfits/index.html.erb
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading" style="color:#33cccc">
                        	Outfits</h1>
<% for outfit in @outfits %>
  <div class="outfit">
    <h2><%= link_to outfit.name, outfit %></h2>
    Items: <%= outfit.items.count %>
  </div>
<% end %>

<p><%= link_to "New Outfit", new_outfit_path %></p>

app/views/outfits/new.html.erb
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading" style="color:#33cccc">
                        	New Outfit
                        </h1>
<%= render 'form' %>

<p><%= link_to "Back to List", user_path(current_user) %></p>

app/views/outfits/show.html.erb
<h1 class='intro'><% @outfit.name %></h1>
 <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
  <div class="small-2 large-2 columns">
    <%= imdb_style_rating_for @outfit, current_user%>
  </div>
  <br>
  <div class="small-2 large-4 columns">
    <% if current_user %>
     Appeal: <%= rating_for @outfit, "Appeal" , disable_after_rate: true %>
      <br>
    <% end %>
  </div>
</div>

<div id="outfits">
  <% for item in @outfit.items %>
    <div class="item">
      <%= image_tag item.image_url(:thumb) if item.image? %>
      <div class="name"><%= item.name %></div>
      <div class="actions">
        <%= link_to "edit", edit_item_path(item) %> |
        <%= link_to "remove", item, :confirm => 'Are you sure?', :method => :delete %>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>
</div>

<p>

  <%= link_to "Add an Item", new_item_path(:outfit_id => @outfit.id) %> |
  <%= link_to "Remove Outfit", @item, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View Outfits", outfits_path %>
</p>

app/views/users/show.html.erb
  <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
<h1  style="color:#33cccc"> <%= "Hello. What do you want to do?" =%> </h1>
<%= button_to "Create Outfit!", new_outfit_path(id: @user.id), :class => "button medium", :method => :get %>
<%= button_to "View Outfits!", outfits_path(id: @user.id), :class => "button medium", :method => :get %>